GroceryStore/Models/Cart.cs
using GroceryStore.Models.CommonProp;
using System.ComponentModel.DataAnnotations;

namespace GroceryStore.Models
{
    public class Cart: SharedProp
    {
        public int CartId { get; set; }
        public int? ProductId { get; set; }
        [Display(Name = "Product name")]
        public string? Productname	 { get; set; }
        public float? price { get; set; }
        public int? Quantity { get; set; }
        public float? Total { get; set; }
        [Display(Name = "Product Image")]

        public string? ProductImage { get; set; }

        public string? Status { get; set; }
        public int? OrderId { get; set; }

    }
}

GroceryStore/Models/ViewComponents/CategoryViewComponent.cs
using GroceryStore.Data;
using Microsoft.AspNetCore.Mvc;

namespace GroceryStore.Models.ViewComponents
{
    public class CategoryViewComponent : ViewComponent
    {
 
        private readonly AppDbContext _db;

        public CategoryViewComponent(AppDbContext context)
        {
            _db = context;
        }
        public IViewComponentResult Invoke()
        {
            return View(_db.categories.ToList());
        }

    }
}

GroceryStore/Models/ViewComponents/FeaturViewComponent.cs
using GroceryStore.Data;
using Microsoft.AspNetCore.Mvc;

namespace GroceryStore.Models.ViewComponents
{
    public class FeaturViewComponent : ViewComponent
    {

        private readonly AppDbContext _db;
        public FeaturViewComponent(AppDbContext context)
        {
            _db = context;
        }
        public IViewComponentResult Invoke()
        {
            return View(_db.features.ToList());
        }

    }
}

GroceryStore/Areas/Dashboard/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GroceryStore.Data;
using GroceryStore.Models;

namespace GroceryStore.Areas.Dashboard.Controllers
{
    [Area("Dashboard")]
    public class CartsController : Controller
    {
        private readonly AppDbContext _context;

        public CartsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Dashboard/Carts
        public async Task<IActionResult> Index(int id)
        {
            return View(await _context.carts.Where(x=>x.OrderId==id).ToListAsync());
        }

        // GET: Dashboard/Carts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.carts
                .FirstOrDefaultAsync(m => m.CartId == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // GET: Dashboard/Carts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dashboard/Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CartId,ProductId,Productname,price,Quantity,Total,ProductImage,Status,OrderId,IsDeleted,IsActive,CreationDate,UpdateDate")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }

        // GET: Dashboard/Carts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.carts.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            return View(cart);
        }

        // POST: Dashboard/Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CartId,ProductId,Productname,price,Quantity,Total,ProductImage,Status,OrderId,IsDeleted,IsActive,CreationDate,UpdateDate")] Cart cart)
        {
            if (id != cart.CartId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.CartId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }

        // GET: Dashboard/Carts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.carts
                .FirstOrDefaultAsync(m => m.CartId == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // POST: Dashboard/Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cart = await _context.carts.FindAsync(id);
            if (cart != null)
            {
                _context.carts.Remove(cart);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartExists(int id)
        {
            return _context.carts.Any(e => e.CartId == id);
        }
    }
}

GroceryStore/Areas/Dashboard/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GroceryStore.Data;
using GroceryStore.Models;
using Microsoft.AspNetCore.Authorization;

namespace GroceryStore.Areas.Dashboard.Controllers
{
    [Authorize]

    [Area("Dashboard")]
    public class ContactsController : Controller
    {
        private readonly AppDbContext _context;

        public ContactsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Dashboard/Contacts
        public async Task<IActionResult> Index()
        {
            return View(await _context.contacts.ToListAsync());
        }

        // GET: Dashboard/Contacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.contacts
                .FirstOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // GET: Dashboard/Contacts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dashboard/Contacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ContactId,StoreAddress,StorePhone,StoreEmail,StoreWebsite,UserName,UserEmail,ContactSubject,ContactMessage")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contact);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(contact);
        }

        // GET: Dashboard/Contacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.contacts.FindAsync(id);
            if (contact == null)
            {
                return NotFound();
            }
            return View(contact);
        }

        // POST: Dashboard/Contacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ContactId,StoreAddress,StorePhone,StoreEmail,StoreWebsite,UserName,UserEmail,ContactSubject,ContactMessage")] Contact contact)
        {
            if (id != contact.ContactId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contact);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactExists(contact.ContactId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contact);
        }

        // GET: Dashboard/Contacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.contacts
                .FirstOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // POST: Dashboard/Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contact = await _context.contacts.FindAsync(id);
            if (contact != null)
            {
                _context.contacts.Remove(contact);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactExists(int id)
        {
            return _context.contacts.Any(e => e.ContactId == id);
        }
    }
}

GroceryStore/Areas/Dashboard/Controllers/HomeController.cs
using GroceryStore.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GroceryStore.Areas.Dashboard.Controllers
{
    [Authorize]

    [Area("Dashboard")]
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;

        public HomeController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            ViewData["contacts"] = _context.contacts.ToList().Count();
            ViewData["features"] = _context.features.ToList().Count();
            ViewData["categories"] = _context.categories.ToList().Count();
            ViewData["products"] = _context.products.ToList().Count();
            return View();
        }
    }
}

GroceryStore/Areas/Dashboard/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GroceryStore.Data;
using GroceryStore.Models;
using Microsoft.AspNetCore.Authorization;

namespace GroceryStore.Areas.Dashboard.Controllers
{
    [Area("Dashboard")]

    [Authorize]
    public class ProductsController : Controller
    {
        private readonly AppDbContext _context;

        public ProductsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Dashboard/Products
        public async Task<IActionResult> Index(int id)
        {
            ViewData["CategoryId"] = id;
            List<Product> result;
            if (id==0)
            {
            result = await _context.products.ToListAsync();

            }
            else
            {
                result = await _context.products.Where(x => x.CategoryId == id).ToListAsync();

            }
            return View(result);
        }

        // GET: Dashboard/Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Dashboard/Products/Create
        public IActionResult Create(int id)
        {
            ViewData["CategoryId"] = id;
            return View();
        }

        // POST: Dashboard/Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ProductDescription,ProductPrice,ProductImg,CategoryId")] Product product, IFormFile ProductImg)
        {
           
                if (ProductImg != null && ProductImg.Length > 0)
                {
                    // Define the path where the image will be saved
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Systemimages", ProductImg.FileName);

                    // Save the image to the folder
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await ProductImg.CopyToAsync(stream);
                    }

                    // Save the image path to your category object (ensure your model has this property)
                    product.ProductImg = ProductImg.FileName;
                }
                else
                {
                    // If the image is required, return an error if it's missing
                    ModelState.AddModelError("CategoryImage", "The image is required.");
                    return View(product);
                }
                _context.Add(product);
                await _context.SaveChangesAsync();

            return RedirectToAction("Index", new { id = product.CategoryId });
        }

        // GET: Dashboard/Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Dashboard/Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,ProductDescription,ProductPrice,ProductImg,CategoryId")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Dashboard/Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Dashboard/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.products.FindAsync(id);
            if (product != null)
            {
                _context.products.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.products.Any(e => e.ProductId == id);
        }
    }
}

GroceryStore/Views/Home/Cart.cshtml
@model IEnumerable<Cart>
@{
    ViewData["Title"] = "Cart";
    int sum = 0;
}

<div class="hero-wrap hero-bread" style="background-image: url('@Url.Content("~/images/bg_1.jpg")');">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Cart</span></p>
                <h1 class="mb-0 bread">My Cart</h1>
            </div>
        </div>
    </div>
</div>

<section class="ftco-section ftco-cart">
    <div class="container">
        <div class="row">
            <div class="col-md-12 ftco-animate">
                <div class="cart-list">
                    <table class="table">
                        <thead class="thead-primary">
                            <tr class="text-center">
                                <th>&nbsp;</th>
                                <th>&nbsp;</th>
                                <th>Product name</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr class="text-center">
                                    <td class="product-remove"><a asp-action="RemoveitemFormCart" asp-controller="Home" asp-route-id="@item.CartId"><span class="ion-ios-close"></span></a></td>
                                    <td>
                                        <img src="~/systemimages/@item.ProductImage" width="100" height="100" />
                                    </td>

                                    <td class="product-name">
                                        <h3>@item.Productname</h3>
                                        <p>Far far away, behind the word mountains, far from the countries</p>
                                    </td>

                                    <td class="price">$@item.price</td>

                                    <td class="quantity">
                                        <div class="input-group mb-3">
                                            <a asp-action="DecreaseQuantity" asp-route-id="@item.CartId" class="quantity-left-minus btn">
                                                <i class="ion-ios-remove"></i>
                                            </a>
                                            <input type="text" name="quantity" class="quantity form-control input-number" value="@item.Quantity" disabled>
                                            <a asp-action="IncreaseQuantity" asp-route-id="@item.CartId" class="quantity-right-plus btn">
                                                <i class="ion-ios-add"></i>
                                            </a>
                                          
                                        </div>
                                        
                                    </td>

                                   
                                    @{
                                        var itemTotal = Convert.ToDouble( item.price) *  Convert.ToDouble(item.Quantity);
                                        sum += Convert.ToInt32(itemTotal);
                                    }

                                    <td class="total">$@itemTotal</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="row justify-content-end">
            <div class="col-lg-4 mt-5 cart-wrap ftco-animate">
                <div class="cart-total mb-3">
                    <h3>Cart Totals</h3>
                    <p class="d-flex">
                        <span>Subtotal</span>
                        <span>@sum JD</span>
                    </p>

                    <hr>
                    <p class="d-flex total-price">
                        <span>Total</span>
                        <span>@sum JD</span>
                    </p>
                </div>
                <p><a asp-action="checkout" asp-controller="Home" asp-route-id=@ViewData["idOrder"] class="btn btn-primary py-3 px-4">Proceed to Checkout</a></p>
            </div>
        </div>
    </div>
</section>

GroceryStore/Views/Home/Contact.cshtml
@model GroceryStore.Models.Contact

@{
    ViewData["Title"] = "Contact";
}

<div class="hero-wrap hero-bread" style="background-image: url('@Url.Content("~/images/bg_1.jpg")');">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Contact us</span></p>
                <h1 class="mb-0 bread">Contact us</h1>
            </div>
        </div>
    </div>
</div>

<section class="ftco-section contact-section bg-light">
    <div class="container">
        <!-- Success Message -->
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-success">
                @TempData["SuccessMessage"]
            </div>
        }

        <!-- Contact Form -->
        <div class="row block-9">
            <div class="col-md-6 order-md-last d-flex">
                <form asp-action="Contact" class="bg-white p-5 contact-form">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="StoreAddress" class="control-label"></label>
                        <input asp-for="StoreAddress" class="form-control" />
                        <span asp-validation-for="StoreAddress" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserName" class="control-label"></label>
                        <input asp-for="UserName" class="form-control" />
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactSubject" class="control-label"></label>
                        <input asp-for="ContactSubject" class="form-control" />
                        <span asp-validation-for="ContactSubject" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactMessage" class="control-label"></label>
                        <input asp-for="ContactMessage" class="form-control" />
                        <span asp-validation-for="ContactMessage" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Send" class="btn btn-primary" />
                    </div>
                </form>
            </div>
            <div class="col-md-6 d-flex">
                <div id="map" class="bg-white">
                    <iframe id="map" src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d6123.992980647293!2d35.86172811114501!3d31.998416411359624!3m2!1i1024!2i768!4f13.1!5e1!3m2!1sar!2sjo!4v1730037589122!5m2!1sar!2sjo" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div>
    </div>
</section>

GroceryStore/Views/Home/DetailsProduct.cshtml
@model GroceryStore.Models.Product

@{
    ViewData["Title"] = "DetailsProduct";
}


<div class="hero-wrap hero-bread" style="background-image: url('@Url.Content("~/images/bg_1.jpg")');">
	<div class="container">
		<div class="row no-gutters slider-text align-items-center justify-content-center">
			<div class="col-md-9 ftco-animate text-center">
				<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span class="mr-2"><a href="index.html">Product</a></span> <span>Product Single</span></p>
				<h1 class="mb-0 bread">Product Single</h1>
			</div>
		</div>
	</div>
</div>

<section class="ftco-section">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 mb-5 ftco-animate">
				<a href="#" class="image-popup"><img src="~/Systemimages/@Model.ProductImg " class="img-fluid" alt="Colorlib Template"></a>
			</div>
			<div class="col-lg-6 product-details pl-md-5 ftco-animate">
				<h3>@Model.ProductName</h3>

				<p class="price"><span>$@Model.ProductPrice</span></p>
				<p>
					@Model.ProductDescription
				</p>
		
				<p><a asp-action="Cart" asp-controller="Home" asp-route-id="@Model.ProductId" class="btn btn-black py-3 px-5">Add to Cart</a></p>

				
			</div>
		</div>
	</div>
</section>

GroceryStore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<section id="home-section" class="hero">
    <div class="home-slider owl-carousel">
        <div class="slider-item" style="background-image: url(images/bg_1.jpg);">
            <div class="overlay"></div>
            <div class="container">
                <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">

                    <div class="col-md-12 ftco-animate text-center">
                        <h1 class="mb-2">We serve Fresh Vegestables &amp; Fruits</h1>
                        <h2 class="subheading mb-4">We deliver organic vegetables &amp; fruits</h2>
                    </div>

                </div>
            </div>
        </div>

        <div class="slider-item" style="background-image: url(images/bg_2.jpg);">
            <div class="overlay"></div>
            <div class="container">
                <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">

                    <div class="col-sm-12 ftco-animate text-center">
                        <h1 class="mb-2">100% Fresh &amp; Organic Foods</h1>
                        <h2 class="subheading mb-4">We deliver organic vegetables &amp; fruits</h2>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

<!-- Featur -->
@await Component.InvokeAsync("Featur")
<!-- Category -->
@await Component.InvokeAsync("Category")

GroceryStore/Views/Home/Product.cshtml
<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10 mb-5 text-center">
                <ul class="product-category">
                    <li><a asp-action="Product" asp-controller="Home" asp-route-id="0">All</a></li>
                    @foreach (var item in (List<Category>)ViewBag.Category)
                    {
                        <li><a asp-action="Product" asp-controller="Home" asp-route-id="@item.CategoryId">@item.CategoryName</a></li>
                    }
                </ul>
            </div>
        </div>
        <div class="row">
            <!-- Row for products -->
            @foreach (var item in Model)
            {
                <div class="col-md-6 col-lg-3 ftco-animate">
                    <div class="product">
                        <a href="#" class="img-prod">
                            <img class="img-fluid" src="~/Systemimages/@item.ProductImg" alt="Product Image">
                            <div class="overlay"></div>
                        </a>
                        <div class="text py-3 pb-4 px-3 text-center">
                            <h3><a href="#">@item.ProductName</a></h3>
                            <div class="d-flex">
                                <div class="pricing">
                                    <p class="price"><span>@item.ProductPrice JD</span></p>
                                </div>
                            </div>
                            <div class="bottom-area d-flex px-3">
                                <div class="m-auto d-flex">
                                    <a asp-action="DetailsProduct" asp-controller="Home" asp-route-id="@item.ProductId" class="add-to-cart d-flex justify-content-center align-items-center text-center">
                                        <span><i class="ion-ios-menu"></i></span>
                                    </a>
                                    <a asp-action="Cart" asp-controller="Home" asp-route-id="@item.ProductId" class="buy-now d-flex justify-content-center align-items-center mx-1">
                                        <span><i class="ion-ios-cart"></i></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>